### ISSUE TITLE
Entradas -> Monto en un pago

### ISSUE THREAD

**Issue by mcoloccini** [arivelli/YACashFlowControl#20]
Que el Monto en un pago se cargue automáticamente con lo que figura en Monto real, y se pueda modificar.

**Comment by arivelli** [comment]
Sólo aplica siempre y cuando el monto en un pago no difiera del monto real (antes de escribirlo)
ver como aplicarlo a la contización del dolar

**Comment by arivelli** [comment]
El pago con tarjetas solo estará disponible si el tipo de entrada es pasivos
