### ISSUE TITLE
Operaciones -> Fecha y monto de operación

### ISSUE THREAD

**Issue by mcoloccini** [arivelli/YACashFlowControl#21]
Que sean obligatorios cuando se concreta la operación. Si se edita una operación que no está completa, no lo sean.
Además ocultar el campo "Completa" al cargar una nueva Operación.

**Comment by arivelli** [comment]
Lo del campo completa hay que ocultarlo en el plan, más precisamente en el plan dentro de entradas, acá es necesario

**Comment by arivelli** [comment]
lo puse como disabled
