### ISSUE TITLE
Generador de Operaciones->Agregar detalle para periodos completos

### ISSUE THREAD

**Issue by arivelli** [arivelli/YACashFlowControl#7]
Tanto para el pago de ciertos impuestos como para cobro de sueldos el detalle debería ser directamente el periodo que cubre, tal vez permitir elegir entre mostrar:

ENERO
ENERO-FEBRERO    |   Primer Bimestre     |    Cuota 1/6

Ver otras opciones

**Comment by mcoloccini** [comment]
ENERO 2020
CUOTA 01/06 - 2020

**Comment by arivelli** [comment]
Opciones de formato de detalle (sólo disponible para recurrente):
-Pago único  (automático para pago único)
-cuota numero/total (CUOTA 01/06) (automático para pago en cuotas)

Para recurrentes disponer estas opciones:
-desde dia/mes hasta dia/mes (período desde ... hasta ...) 
-cuota anualizada (CUOTA 01/06 - 2020) 
-mes/año - mes/año (ENERO 2020)

**Comment by arivelli** [comment]
Lista la interfaz
